# Generated by Django 4.1 on 2022-08-29 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_alter_company_name_alter_country_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.TextField()),
                ('reward', models.IntegerField(default=0)),
                ('contents', models.TextField()),
                ('Tech_stack', models.TextField()),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='job_post', to='companies.company')),
            ],
            options={
                'verbose_name': '채용공고',
                'db_table': 'job_posts',
            },
        ),
    ]
