# Generated by Django 4.1 on 2022-08-30 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_company_name_alter_country_name_and_more'),
        ('job_posts', '0003_rename_company_id_jobpost_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='job_post', to='companies.company'),
        ),
    ]
